"""
reconciliation.py - Split-Brain Recovery & LLM Semantic Arbiter for Clew V5
Identifies divergent MultiValueRegister semantic entries generated by concurrent writes
across network partitions, invokes the local LLM via Jinja2 template to arbitrate,
and writes resolved state back to GraphCRDT engine.
"""

import os
import time
import json
import asyncio
import jinja2
from typing import List, Dict, Any, Optional, Tuple

from crdt_engine import GraphCRDT, MultiValueRegister
from router import ModelRouter

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_PATH = os.path.join(BASE_DIR, "templates", "arbiter_prompt.jinja2")

def _extract_json_payload(text: str) -> Optional[Dict[str, Any]]:
    """Extracts JSON object from model output text."""
    if not text:
        return None
    clean_text = text.strip()
    if clean_text.startswith("```"):
        lines = clean_text.splitlines()
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        clean_text = "\n".join(lines).strip()
    try:
        return json.loads(clean_text)
    except Exception:
        import re
        match = re.search(r"\{.*\}", clean_text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(0))
            except Exception:
                pass
        return None

class ReconciliationEngine:
    """
    Reconciliation layer for identifying and arbitrating divergent semantic MVR entries.
    """

    def __init__(self, crdt_instance: GraphCRDT, router_instance: Optional[ModelRouter] = None):
        self.crdt = crdt_instance
        self.router = router_instance if router_instance is not None else ModelRouter()

    def find_divergences(self) -> List[Dict[str, Any]]:
        """
        Calls self.crdt.get_divergent_mvr_entries().
        Returns a list of structured divergence objects containing target IDs, property keys, and candidates.
        """
        divergent_map = self.crdt.get_divergent_mvr_entries()
        divergence_list = []
        for (target_id, prop_key), mvr in divergent_map.items():
            candidates = []
            for ts, val in mvr.entries.items():
                node_id = ts[2] if len(ts) >= 3 else ""
                candidates.append({
                    "value": val,
                    "hlc": ts,
                    "node_id": node_id
                })
            divergence_list.append({
                "target_id": target_id,
                "property_key": prop_key,
                "candidates": candidates
            })
        return divergence_list

    async def reconcile_divergences(self) -> int:
        """
        Arbitrates divergent MVR properties using the LLM Arbiter and applies resolutions.
        Returns total count of successfully arbitrated properties.
        """
        divergences = self.find_divergences()
        if not divergences:
            return 0

        if not os.path.exists(TEMPLATE_PATH):
            raise FileNotFoundError(f"Arbiter template not found at {TEMPLATE_PATH}")

        with open(TEMPLATE_PATH, "r", encoding="utf-8") as f:
            template_str = f.read()

        template = jinja2.Template(template_str)
        prompt = template.render(divergences=divergences)

        res = self.router.execute_completion(
            system_prompt=prompt,
            tier="GENERALIST",
            options={"temperature": 0.0}
        )
        if hasattr(res, "__await__") or asyncio.iscoroutine(res):
            res = await res

        if isinstance(res, str):
            payload = _extract_json_payload(res)
        elif isinstance(res, dict):
            payload = res
        else:
            payload = None

        if not payload or "resolutions" not in payload:
            return 0

        resolved_count = 0
        now_ts = time.time()
        for idx, item in enumerate(payload.get("resolutions", [])):
            t_id = item.get("target_id")
            p_key = item.get("property_key")
            winning_val = item.get("winning_value")

            if t_id and p_key and winning_val is not None:
                key = (t_id, p_key)
                res_hlc = (now_ts, idx, "arbiter")
                if key in self.crdt.semantic_mvr:
                    self.crdt.semantic_mvr[key].resolve(winning_val, res_hlc)
                    resolved_count += 1

        return resolved_count
